---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels: 
    app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetrPort: 80
  selector:
    app: frontend
  type: LoadBalancer
...
