---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: frontend-temp
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prathamesh5145/backend:v1
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
...