---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  template:
    metadata:
      name: backend-temp
      labels: 
        app: backend
    spec:
      containers:
        - name: backend
          image: prathamesh5145/frontend:latest
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
...
      